using DiscUtils.Streams;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WinBox_Maker
{
    internal class Consts
    {
        static public string[] defaultDeletePackages =
        {
            "*Microsoft-Windows-LanguageFeatures-Handwriting-en-us",
            "*Microsoft-Windows-LanguageFeatures-OCR-en-us",
            "*Microsoft-Windows-LanguageFeatures-Speech-en-us",
            "*Microsoft-Windows-LanguageFeatures-TextToSpeech-en-us",
            "*Microsoft-Windows-MediaPlayer",
            "*Microsoft-Windows-MediaPlayer",
            "*Microsoft-Windows-MediaPlayer",
            "*Microsoft-Windows-MediaPlayer",
            "*Microsoft-Windows-TabletPCMath",
            "*Microsoft-Windows-Wallpaper-Content-Extended",
            "*Microsoft-Windows-ContactSupport",
            "*Microsoft-Windows-QuickAssist"
        };

        static public string[] defaultDisableFeatures =
        {
            "Windows-Defender", //it will probably only work for Windows server
            "Windows-Defender-GUI"
        };

        static public string[] defaultDeleteProvisionedPackages =
        {
            "*Clipchamp.Clipchamp",
            "*Microsoft.BingNews",
            "*Microsoft.BingWeather",
            "*Microsoft.GamingApp",
            "*Microsoft.GetHelp",
            "*Microsoft.Getstarted",
            "*Microsoft.MicrosoftOfficeHub",
            "*Microsoft.MicrosoftSolitaireCollection",
            "*Microsoft.People",
            "*Microsoft.PowerAutomateDesktop",
            "*Microsoft.Todos",
            "*Microsoft.WindowsAlarms",
            "*microsoft.windowscommunicationsapps",
            "*Microsoft.WindowsFeedbackHub",
            "*Microsoft.WindowsMaps",
            "*Microsoft.WindowsSoundRecorder",
            "*Microsoft.Xbox.TCUI",
            "*Microsoft.XboxGamingOverlay",
            "*Microsoft.XboxGameOverlay",
            "*Microsoft.XboxSpeechToTextOverlay",
            "*Microsoft.YourPhone",
            "*Microsoft.ZuneMusic",
            "*Microsoft.ZuneVideo",
            "*MicrosoftCorporationII.MicrosoftFamily",
            "*MicrosoftCorporationII.QuickAssist",
            "*MicrosoftTeams",
            "*Microsoft.Windows.SecHealthUI",
            "*Microsoft.XboxIdentityProvider",
            "*Microsoft.XboxApp",
            "*Microsoft.WindowsStore",
            "*Microsoft.WindowsCamera",
            "*Microsoft.WindowsCalculator",
            "*Microsoft.Windows.Photos",
            "*Microsoft.StorePurchaseApp",
            "*Microsoft.SkypeApp",
            "*Microsoft.OneConnect",
            "*Microsoft.Office.OneNote",
            "*Microsoft.MicrosoftStickyNotes",
            "*Microsoft.3DBuilder",
            "*Microsoft.Messaging",
            "*Microsoft.ScreenSketch",
            "*Microsoft.YourPhone",
            "*Microsoft.MiracastView",
            "*Microsoft.549981C3F5F10",
            "*Microsoft.MixedReality.Portal",
            "*Microsoft.Microsoft3DViewer",
            "*Microsoft.Wallet",
            "*Microsoft.MSPaint",
            "*Microsoft.Windows.Cortana",
            "*Microsoft.XboxGame",
            "*CortanaSupport"
        };

        static public string[] defaultStopOrDeleteSchtasks = {
            @"\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser",
            @"\Microsoft\Windows\Application Experience\ProgramDataUpdater",
            @"\Microsoft\Windows\Autochk\Proxy",
            @"\Microsoft\Windows\Customer Experience Improvement Program\Consolidator",
            @"\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask",
            @"\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip",
            @"\Microsoft\Windows\AppID\SmartScreenSpecific",
            @"\Microsoft\Windows\Application Experience\AitAgent",
            @"\Microsoft\Windows\Application Experience\StartupAppTask",
            @"\Microsoft\Windows\ApplicationData\appuriverifierdaily",
            @"\Microsoft\Windows\ApplicationData\appuriverifierinstall",
            @"\Microsoft\Windows\Device Information\Device",
            @"\Microsoft\Windows\Diagnosis\Scheduled",
            @"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector",
            @"\Microsoft\Windows\LanguageComponentsInstaller\Installation",
            @"\Microsoft\Windows\LanguageComponentsInstaller\Uninstallation",
            @"\Microsoft\Windows\Maintenance\WinSAT",
            @"\Microsoft\Windows\Maps\MapsToastTask",
            @"\Microsoft\Windows\Maps\MapsUpdateTask",
            @"\Microsoft\Windows\Mobile Broadband Accounts\MNO Metadata Parser",
            @"\Microsoft\Windows\MobilePC\HotStart",
            @"\Microsoft\Windows\MUI\LPRemove",
            @"\Microsoft\Windows\NetTrace\GatherNetworkInfo",
            @"\Microsoft\Windows\Power Efficiency Diagnostics\AnalyzeSystem",
            @"\Microsoft\Windows\RAC\RacTask",
            @"\Microsoft\Windows\RemoteAssistance\RemoteAssistanceTask",
            @"\Microsoft\Windows\RetailDemo\CleanupOfflineContent",
            @"\Microsoft\Windows\SettingSync\BackgroundUploadTask",
            @"\Microsoft\Windows\SettingSync\BackupTask",
            @"\Microsoft\Windows\SettingSync\NetworkStateChangeTask",
            @"\Microsoft\Windows\Setup\EOSNotify",
            @"\Microsoft\Windows\Setup\EOSNotify2",
            @"\Microsoft\Windows\Setup\SetupCleanupTask",
            @"\Microsoft\Windows\Speech\SpeechModelDownloadTask",
            @"\Microsoft\Windows\SystemRestore\SR",
            @"\Microsoft\Windows\Time Synchronization\SynchronizeTime",
            @"\Microsoft\Windows\Windows Error Reporting\QueueReporting",
            @"\Microsoft\Windows\WindowsBackup\ConfigNotification",
            @"\Microsoft\Windows\WS\License Validation",
            @"\Microsoft\Windows\WS\WSRefreshBannedAppsListTask",
            @"\Microsoft\XblGameSave\XblGameSaveTask",
            @"\Microsoft\XblGameSave\XblGameSaveTaskLogon",
            @"Microsoft\Windows\Settings",
            @"Microsoft\Windows\Shell",
            @"Microsoft\Windows\Explorer",
            @"\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser",
            @"\Microsoft\Windows\Application Experience\ProgramDataUpdater",
            @"\Microsoft\Windows\Autochk\Proxy",
            @"\Microsoft\Windows\Customer Experience Improvement Program\Consolidator",
            @"\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask",
            @"\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip",
            @"\Microsoft\Windows\Application Experience\AitAgent",
            @"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector",
            @"\Microsoft\Windows\Maintenance\WinSAT",
            @"\Microsoft\Windows\Media Center\ActivateWindowsSearch",
            @"\Microsoft\Windows\Media Center\ConfigureInternetTimeService",
            @"\Microsoft\Windows\Media Center\DispatchRecoveryTasks",
            @"\Microsoft\Windows\Media Center\ehDRMInit",
            @"\Microsoft\Windows\Media Center\InstallPlayReady",
            @"\Microsoft\Windows\Media Center\mcupdate",
            @"\Microsoft\Windows\Media Center\MediaCenterRecoveryTask",
            @"\Microsoft\Windows\Media Center\ObjectStoreRecoveryTask",
            @"\Microsoft\Windows\Media Center\OCURActivate",
            @"\Microsoft\Windows\Media Center\OCURDiscovery",
            @"\Microsoft\Windows\Media Center\PBDADiscovery",
            @"\Microsoft\Windows\Media Center\PBDADiscoveryW1",
            @"\Microsoft\Windows\Media Center\PBDADiscoveryW2",
            @"\Microsoft\Windows\Media Center\PvrRecoveryTask",
            @"\Microsoft\Windows\Media Center\PvrScheduleTask",
            @"\Microsoft\Windows\Media Center\RegisterSearch",
            @"\Microsoft\Windows\Media Center\ReindexSearchRoot",
            @"\Microsoft\Windows\Media Center\SqlLiteRecoveryTask",
            @"\Microsoft\Windows\Media Center\UpdateRecordPath",
            @"\Microsoft\Windows\UpdateOrchestrator\Schedule Scan",
            @"\Microsoft\Windows\UpdateOrchestrator\USO_UxBroker",
            @"\Microsoft\Windows\DiskCleanup\SilentCleanup",
            @"\Microsoft\Windows\Backup\ScheduledBackup",
            @"\Microsoft\Windows\WindowsUpdate\"
        };

        static public string[] defaultDeletePaths = {
            "Windows\\System32\\rgnupdt.exe",
            "Windows\\System32\\wuaueng.dll",
            "Windows\\System32\\usosvc.dll",
            "Windows\\System32\\qmgr.dll",
            "Windows\\System32\\Tasks\\Microsoft\\OneDrive",
            "Windows\\System32\\OneDriveSetup.exe",
            "Windows\\SysWOW64\\OneDriveSetup.exe",
            "Program Files (x86)\\Windows Defender",
            "Program Files (x86)\\Windows Defender Advanced Threat Protection",
            "Program Files\\Windows Defender",
            "Program Files\\Windows Defender Advanced Threat Protection",
            "ProgramData\\Microsoft\\Windows Defender",
            "ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\System Tools\\Windows Defender.lnk",
            "Windows\\SystemApps\\Microsoft.PPIProjection_cw5n1h2txyewy",
            //"Windows\\SystemApps\\ContactSupport_cw5n1h2txyewy",
            //"Windows\\SystemApps\\Microsoft.Windows.Cortana_cw5n1h2txyewy"
        };

        static public string[] defaultStopServicesList = {
            "SecurityHealthService",
            "Sense",
            "WdBoot",
            "WdFilter",
            "WdNisDrv",
            "WdNisSvc",
            "Superfetch",
            "OneSyncSvc",
            "OfficeClickToRun",
            "OneDrive",
            "Cortana",
            "SyncHost",
            "CompatTelRunner",
            "UsoSvc",
            "wlidsvcNetwork",

            "WpnUserService",
            "ClickToRunSvc",
            "VSS",

            "edgeupdate",
            "edgeupdatem",
            "wbengine",
            "wuauserv",
            "RemoteRegistry",
            "WSearch",
            "SysMain",
            "WerSvc",
            "shellhwdetection",
            "SSDPSRV",
            "TermService",
            "napagent",
            "WinDefend",
            "wlidsvc",
            "DiagTrack",
            "dmwappushservice",
            "Dosvc",
            "XboxGipSvc",
            "XblAuthManager",
            "XblGameSave",
            "XboxNetApiSvc",
            "WaaSMedicSvc",
            "WdNisSvc",
            "wscsvc",
            "wisvc",

            "PhoneSvc",
            "SessionEnv",
            "UmRdpService",
            "svsvc",
            "TapiSrv",
            "SDRSVC",
            "WbioSrvc",
            "Wecsvc",
            "ClipSVC",
            "WpnService",
            "PushToInstall",
            "WinRM",
            "workfolderssvc",
            "WwanSvc",
            "AarSvc",
            "cbdhsvc",
            "CloudBackupRestoreSvc",
            "CDPUserSvc",
            "ConsentUxUserSvc",
            "PimIndexMaintenanceSvc",
            "UnistoreSvc",
            "wercplsupport",
            "PcaSvc",
            "RasMan",
            "DevicePickerUserSvc",
            "DevicesFlowUserSvc",
            "BcastDVRUserService",
            "MessagingService",
            "UdkUserSvc",
            "UserDataSvc",
            "CscService",
            "CSC"
        };
    }
}
